### ISSUE TITLE
Problem installing on debian 9 with foreman 1.17.1

### ISSUE THREAD

**Issue by selund** [tristanrobert/foreman_proxmox#28]
## Prerequisites

Please check (put an X between the brackets) the following items before posting any issue:

* [X] Have you check that no [issue](https://github.com/tristanrobert/foreman_proxmox/issues) already exists and could match yours?

* [X] Have you read the [contributing code](CONTRIBUTING.md)?

## Description

I'm trying to install the plugin on a debian 9.4  with foreman 1.17.1 installed with foreman-installer, however I experience trouble starting foreman after installing the plugin. 
In the apache log I find that the problem is caused by an uninitialized constant TheForemanProxmox::Engine::Uglifier. 
Trying to do a "foreman-rake db:migrate --trace" also trigger a similar problem  "NameError: uninitialized constant TheForemanProxmox::Engine::Uglifier " 

## Environment
OS: Debian 9.4 (up to date)
ruby: 2.3.3p222 (from Debian) 
foreman 1.17.1 (upgraded from 1.16

## Version
fog-proxmox 0.4.0 from https://github.com/fog/fog-proxmox.git (at master@0f191c7)
the_foreman_proxmox 0.3.1 from https://github.com/tristanrobert/foreman_proxmox.git (at master@ade2325)

## Steps to reproduce

add the_foreman_proxmox and fog-proxmox to ~foreman/bundler.d/Gemfile.local.rb 
/usr/bin/foreman-ruby /usr/bin/bundle install
restart apache 

### Reproduces how often:

Every time

## Additional Information
I'm not sure what more information I can give to help, Logs?

**Comment by tristanrobert** [comment]
Hello,
you need to add `gem 'uglifier' ` in /usr/share/foreman/bundler.d/Gemfile.local.rb.
Nodejs is required too.
deb packages will be soon available and could ease installation.

**Comment by selund** [comment]
Thank's that solved my problem.  
I see that having some containers on my existing proxmox server creates some trouble, but as far as I understand, there hasn't been done much work on containers yet? If you want bugreports on container issues at this time, please let me know.

**Comment by tristanrobert** [comment]
Containers is planned next release. I would tell when it's out.
